# Generated by Django 4.1.3 on 2023-02-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='start_project',
            field=models.CharField(max_length=255, verbose_name='Старт проекта'),
        ),
    ]
