# Generated by Django 4.1.3 on 2023-02-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_date_pub_alter_form_start_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='platform',
            field=models.CharField(max_length=255, verbose_name='Платформа проекта'),
        ),
        migrations.AlterField(
            model_name='form',
            name='project_status',
            field=models.CharField(max_length=255, verbose_name='Статус проекта'),
        ),
    ]
