# Generated by Django 4.1.3 on 2022-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, verbose_name='Тип проекта')),
                ('platform', models.CharField(max_length=250, verbose_name='Платформа проекта')),
                ('condition', models.CharField(max_length=250, verbose_name='Состояние проекта')),
                ('when', models.CharField(max_length=250, verbose_name='Когда начать проект')),
                ('name', models.CharField(max_length=250, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=250, verbose_name='Телефон заказчика')),
                ('email', models.CharField(max_length=250, verbose_name='Email заказчика')),
                ('comment', models.CharField(max_length=250, verbose_name='Комметнарий заказчика')),
                ('file', models.FileField(upload_to='media/form/')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Архивный')], max_length=250, verbose_name='Статус проекта')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(upload_to='media/project/')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
